# Generated by Django 3.0.4 on 2020-04-04 11:11

import PlayBooksWeb.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includedfolder',
            name='path',
            field=models.CharField(max_length=10000, validators=[PlayBooksWeb.validators.validate_path_access]),
        ),
    ]
