# Generated by Django 3.0.4 on 2020-03-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='playbook',
            name='cover_img',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='playbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playbook',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('playpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayBooksApp.Playpage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayBooksApp.PlaybookSection')),
            ],
        ),
        migrations.AddField(
            model_name='playbooksection',
            name='pages',
            field=models.ManyToManyField(related_name='sections', related_query_name='section', through='PlayBooksApp.SectionContent', to='PlayBooksApp.Playpage'),
        ),
        migrations.AddField(
            model_name='playbooksection',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='PlayBooksApp.Playbook'),
        ),
    ]
