# Generated by Django 3.0.4 on 2020-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksApp', '0003_auto_20200328_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='playpage',
            name='check_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playpage',
            name='http_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playpage',
            name='offline_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='cover_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
