# Generated by Django 3.0.4 on 2020-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksApp', '0004_auto_20200329_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playpage',
            old_name='http_source',
            new_name='source',
        ),
        migrations.AddField(
            model_name='playpage',
            name='offline_store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playpage',
            name='source_type',
            field=models.CharField(default='HTTP', max_length=500),
        ),
    ]
