# Generated by Django 3.0.4 on 2020-04-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksApp', '0005_auto_20200401_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playpage',
            name='offline_copy',
        ),
    ]
