# Generated by Django 3.0.4 on 2020-04-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksWeb', '0002_auto_20200404_1311'),
        ('PlayBooksApp', '0006_remove_playpage_offline_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playpage',
            name='included_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PlayBooksWeb.IncludedFolder'),
        ),
        migrations.AddField(
            model_name='playpage',
            name='included_folder_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
