# Generated by Django 3.0.4 on 2020-04-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayBooksApp', '0007_auto_20200406_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playpage',
            name='included_folder_path',
        ),
    ]
