# Generated by Django 3.0.4 on 2020-04-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlayBooksApp', '0009_auto_20200410_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbooksection',
            options={'ordering': ['section_position']},
        ),
        migrations.AlterModelOptions(
            name='sectioncontent',
            options={'ordering': ['page_position']},
        ),
        migrations.AddField(
            model_name='playpage',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='page_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='playpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_contents', related_query_name='section_contents', to='PlayBooksApp.Playpage'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_contents', related_query_name='section_contents', to='PlayBooksApp.PlaybookSection'),
        ),
    ]
