# Generated by Django 3.0.4 on 2020-04-11 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlayBooksApp', '0010_auto_20200411_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
